
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ares-app-ingress
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
    - host: app.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ares-app
                port:
                  number: 3000
