
apiVersion: v1
kind: Service
metadata:
  name: ares-app
  labels:
    app: ares-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ares-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      nodePort: {{.Values.nodePort.port}}
      protocol: TCP
