
apiVersion: v1
kind: Secret
metadata:
  name: ares-db-credentials
  labels:
    app: ares-app
type: Opaque
stringData:
  # Env vars for the app
  DB_HOST: mysql              # service name below
  DB_PORT: "3306"
  DB_USERNAME: {{ .Values.mysql.dbUser | quote }}
  DB_PASSWORD: {{ .Values.mysql.dbPassword | quote }}
  DB_DATABASE: {{ .Values.mysql.dbName | quote }}
  APP_PORT: "{{ .Values.app.port }}"
  DB_LESS: {{ .Values.app.dbLess | quote }}

  # MySQL-side secrets
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
